on: [push]

name: CI

jobs:
  build_web_app:
    name: Web App
    runs-on: ubuntu-latest
    env:
      CHAIN: "kovan"
      OIDC_ISSUER: https://oidc.web3-login.net/kovan
      OIDC_CLIENT_ID: "0x3B8270447b913d0b935e09d1C2daEc3F5CDD968f"
      OIDC_REDIRECT_URI: https://web3-login.net/nft-login-demo/
      OIDC_POST_LOGOUT_REDIRECT_URI: https://web3-login.net/nft-login-demo/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install node dependencies
        run: npm install
      - name: Build App
        run: PUBLIC_URL=/nft-login-demo npm run showcase:build && cp -R public gh-public

      - name: Build App for kovan
        env:
          CHAIN: "kovan"
          OIDC_ISSUER: https://oidc.web3-login.net/kovan
          OIDC_CLIENT_ID: "0x3B8270447b913d0b935e09d1C2daEc3F5CDD968f"
          OIDC_REDIRECT_URI: https://web3-login.net/nft-login-demo/kovan/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://web3-login.net/nft-login-demo/kovan/
        run: PUBLIC_URL=/nft-login-demo/kovan npm run showcase:build && cp -R public gh-public/kovan
      - name: Build App for okt
        env:
          CHAIN: "okt"
          OIDC_ISSUER: https://nft-login.net/okt/
          OIDC_CLIENT_ID: "0xf0263c1D56A167cDCF72086071f96CbB8a077AE9"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/okt/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/okt/
        run: PUBLIC_URL=/nft-login-demo/okt npm run showcase:build && cp -R public gh-public/okt
      - name: Build App for heco
        env:
          CHAIN: "heco"
          OIDC_ISSUER: https://nft-login.net/heco/
          OIDC_CLIENT_ID: "0xa0d4E5CdD89330ef9d0d1071247909882f0562eA"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/heco/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/heco/
        run: PUBLIC_URL=/nft-login-demo/heco npm run showcase:build && cp -R public gh-public/heco
      - name: Build App for celo
        env:
          CHAIN: "celo"
          OIDC_ISSUER: https://nft-login.net/celo/
          OIDC_CLIENT_ID: "0xBa4e569A5156C00348B89653968c2C294f80E151"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/celo/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/celo/
        run: PUBLIC_URL=/nft-login-demo/celo npm run showcase:build && cp -R public gh-public/celo
      - name: Build App for polygon
        env:
          CHAIN: "polygon"
          OIDC_ISSUER: https://nft-login.net/polygon/
          OIDC_CLIENT_ID: "0x8866afd737201d9Fcc16438b65f1E3db7A3A5Ddb"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/polygon/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/polygon/
        run: PUBLIC_URL=/nft-login-demo/polygon npm run showcase:build && cp -R public gh-public/polygon
      - name: Build App for metis
        env:
          CHAIN: "metis"
          OIDC_ISSUER: https://nft-login.net/metis/
          OIDC_CLIENT_ID: "0x8866afd737201d9Fcc16438b65f1E3db7A3A5Ddb"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/metis/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/metis/
        run: PUBLIC_URL=/nft-login-demo/metis npm run showcase:build && cp -R public gh-public/metis

      - name: Build App for theta
        env:
          CHAIN: "theta"
          OIDC_ISSUER: https://nft-login.net/theta/
          OIDC_CLIENT_ID: "0x8fb36197889f23E76e68E3FD57c6063A21DdE897"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/theta/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/theta/
        run: PUBLIC_URL=/nft-login-demo/theta npm run showcase:build && cp -R public gh-public/theta

      - name: Build App for avax
        env:
          CHAIN: "avax"
          OIDC_ISSUER: https://nft-login.net/avax/
          OIDC_CLIENT_ID: "0x51320F31d30c56c8107D82b4C67C5EdDfCa88bc2"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/avax/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/avax/
        run: PUBLIC_URL=/nft-login-demo/avax npm run showcase:build && cp -R public gh-public/avax

      - name: Build App for binance
        env:
          CHAIN: "binance"
          OIDC_ISSUER: https://nft-login.net/binance/
          OIDC_CLIENT_ID: "0x886B6781CD7dF75d8440Aba84216b2671AEFf9A4"
          OIDC_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/binance/
          OIDC_POST_LOGOUT_REDIRECT_URI: https://nft-login.github.io/nft-login-demo/binance/
        run: PUBLIC_URL=/nft-login-demo/binance npm run showcase:build && cp -R public gh-public/binance

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-public
          keep_files: true
